### ISSUE TITLE
タグの並び順について

### ISSUE THREAD

**Issue by yuzuka4573** [birdgeH/smap#21]
五十音順（default)と数順にできれば楽な気がする

**Comment by uehara1414** [comment]
お気に入りを上に表示するとかも欲しい。
最終的にはSlackのチャンネルみたいな表示にしたいと思ってるんだけど、どうでしょうか

**Comment by yuzuka4573** [comment]
ユーザー登録したらお気に入りタグの保存とかできるといいね
もちろんslack形式のやつも
基本機能は上記のようにするといいかも？
