### ISSUE TITLE
タグのタイトルの問題

### ISSUE THREAD

**Issue by yuzuka4573** [birdgeH/smap#24]
データベース上にはfieldを書く欄があるんだけどApp本体にはそこに関するものがない
なお、内部から書き換えようとするとFieldが要求される

**Comment by uehara1414** [comment]
今の所いらなそうだから消しておきます

**Comment by yuzuka4573** [comment]
正直なところをいうと、Discriptionに地名とか入れるのってどうなのかなー…っと思ったり
任意でつけられるとかの方がいいような

**Comment by uehara1414** [comment]
じゃあとりあえず required=False って感じにするだけにしておくわ
